CREATE TABLE [dbo].[Item]
(
	[ItemID] NVARCHAR(30) NOT NULL,
	[ItemType] NVARCHAR(20) NOT NULL,
	[PriorityLevel] NVARCHAR(20) NOT NULL, 
    [OriginatorID] NVARCHAR(30) NOT NULL,
	[RecipientID] NVARCHAR(30) NULL,
	[TransFromID] NVARCHAR(30) NULL,
	[Title] NVARCHAR(100) NOT NULL,
	[Body] NVARCHAR(1000) NOT NULL,
	[DateTimeCreated] DATETIME NOT NULL,
	CONSTRAINT PK_ITEM PRIMARY KEY(ItemID),
	CONSTRAINT CHK_ITEM_PRIORITYLEVEL CHECK(PriorityLevel IN ('HIGH', 'NORMAL', 'LOW')),
	CONSTRAINT CHK_TYPE_RECIPIENT CHECK(ItemType = 'DATA' AND RecipientID IS NULL 
										OR ItemType = 'MESSAGE' AND RecipientID IS NOT NULL)
	)