CREATE TABLE [dbo].[RemoveFlag]
(
	[ItemID] NVARCHAR(30) NOT NULL,
	[OriginatorID] NVARCHAR(30) NOT NULL, 
	[DateTimeFlagged] DATETIME NOT NULL,
    CONSTRAINT PK_REMOVEFLAG PRIMARY KEY(ItemID)
	-- NO FOREIGN KEY ADDED BECAUSE EACH ROW IN THIS TABE NECCESSARILY 
	-- HAS NO ASSOCIATED ROW IN THE ITEM TABLE AS IT HAS BEEN REMOVED.
)
