CREATE TABLE [dbo].[TransferLog]
(
	[ItemID] NVARCHAR(30) NOT NULL,
	[OriginatorId] NVARCHAR(30) NOT NULL,
	[IsRemoveFlag] TINYINT NOT NULL,
	[TransFromID] NVARCHAR(30) NOT NULL,
	[DateTimeTransfered] DATETIME NOT NULL,
    CONSTRAINT PK_TRANSFERLOG PRIMARY KEY (ItemID, IsRemoveFlag, TransFromID)
	-- NO FOREIGN KEYS USED AS THIS LOG NEEDS TO MAINTAIN ENTRIES AFTER 
	-- DATA POINTS ARE REMOVED OR GROOMED.
)
