//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANET_DTN_Mock_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MANET_DTN_MOCKEntities : DbContext
    {
        public MANET_DTN_MOCKEntities()
            : base("name=MANET_DTN_MOCKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<RemoveFlag> RemoveFlags { get; set; }
        public virtual DbSet<TransferLog> TransferLogs { get; set; }
        public virtual DbSet<ItemIDList> ItemIDLists { get; set; }
        public virtual DbSet<RemoveIDList> RemoveIDLists { get; set; }
    }
}
