//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANET_DTN_Mock_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string ItemID { get; set; }
        public string ItemType { get; set; }
        public string PriorityLevel { get; set; }
        public string OriginatorID { get; set; }
        public string RecipientID { get; set; }
        public string TransFromID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
    }
}
