//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANET_DTN_Mock_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoveFlag
    {
        public string ItemID { get; set; }
        public string OriginatorID { get; set; }
        public System.DateTime DateTimeFlagged { get; set; }
    }
}
